-- PostgreSQL schema. Applied on startup by app/db.py; every statement is
-- idempotent, so it is safe to run against an existing database. Same
-- Postgres server/database as the AMC app, but its own schema and tables.

CREATE SCHEMA IF NOT EXISTS ela_read;

-- Content tables: upserted from content/books/*.json and
-- content/lessons/<book_id>/*.json by app/content_loader.py, run manually
-- (never automatically on app startup). Never edit these by hand; edit the
-- JSON and re-run the loader.
CREATE TABLE IF NOT EXISTS books (
    book_id         TEXT PRIMARY KEY,
    title           TEXT NOT NULL,
    author          TEXT NOT NULL,
    source_pdf      TEXT,
    chapter_count   INTEGER
);

CREATE TABLE IF NOT EXISTS lessons (
    lesson_id           TEXT PRIMARY KEY,
    book_id             TEXT NOT NULL REFERENCES books(book_id),
    chapter             INTEGER NOT NULL,
    part                INTEGER NOT NULL,
    parts_in_chapter    INTEGER NOT NULL,
    title               TEXT NOT NULL,
    word_count          INTEGER NOT NULL,
    estimated_minutes   INTEGER NOT NULL,
    ord                 INTEGER NOT NULL,      -- global reading order within the book
    paragraphs_json     TEXT NOT NULL          -- JSON array of paragraph strings
);
CREATE UNIQUE INDEX IF NOT EXISTS lessons_book_ord ON lessons (book_id, ord);

CREATE TABLE IF NOT EXISTS mc_questions (
    id                      TEXT PRIMARY KEY,  -- e.g. fwtbt-ch01-l01-q1
    lesson_id               TEXT NOT NULL REFERENCES lessons(lesson_id) ON DELETE CASCADE,
    ord                     INTEGER NOT NULL,
    skill                   TEXT NOT NULL,
    paragraph_refs_json     TEXT NOT NULL,
    prompt                  TEXT NOT NULL,
    choices_json            TEXT NOT NULL,     -- {"A": "...", "B": "...", ...}
    correct                 TEXT NOT NULL,     -- e.g. "B" - never sent to the client before grading
    rationale               TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS mc_questions_lesson ON mc_questions (lesson_id, ord);

CREATE TABLE IF NOT EXISTS open_questions (
    id              TEXT PRIMARY KEY,          -- e.g. fwtbt-ch01-l01-or1
    lesson_id       TEXT NOT NULL REFERENCES lessons(lesson_id) ON DELETE CASCADE,
    ord             INTEGER NOT NULL,
    skill           TEXT NOT NULL,
    prompt          TEXT NOT NULL,
    guidance_json   TEXT NOT NULL              -- JSON array of guidance bullet strings
);
CREATE INDEX IF NOT EXISTS open_questions_lesson ON open_questions (lesson_id, ord);

-- Student tables: never touched by the loader.
CREATE TABLE IF NOT EXISTS students (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS students_name_lower ON students (lower(name));

CREATE TABLE IF NOT EXISTS lesson_progress (
    student_id          INTEGER NOT NULL REFERENCES students(id),
    lesson_id           TEXT NOT NULL REFERENCES lessons(lesson_id),
    mc_answers_json      TEXT NOT NULL DEFAULT '{}',   -- {"fwtbt-ch01-l01-q1": "B", ...}
    open_responses_json  TEXT NOT NULL DEFAULT '{}',   -- {"fwtbt-ch01-l01-or1": "student's answer", ...}
    completed            INTEGER NOT NULL DEFAULT 0,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (student_id, lesson_id)
);

-- The reading position marker: where a student resumes a book.
CREATE TABLE IF NOT EXISTS bookmarks (
    student_id          INTEGER NOT NULL REFERENCES students(id),
    book_id              TEXT NOT NULL REFERENCES books(book_id),
    current_lesson_id    TEXT NOT NULL REFERENCES lessons(lesson_id),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (student_id, book_id)
);

CREATE TABLE IF NOT EXISTS vocabulary (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      INTEGER NOT NULL REFERENCES students(id),
    lesson_id       TEXT NOT NULL REFERENCES lessons(lesson_id),
    selected_text   TEXT NOT NULL,
    meaning         TEXT NOT NULL,
    context_note    TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS vocabulary_student ON vocabulary (student_id, created_at DESC);
